### PR TITLE
Support multiple package.json paths

### LINKED ISSUE #6: Support multiple package.json files
Hi thanks for this package!

I was about to post this issue in `rollup-plugin-auto-external` but this one seems to be more active!

I might be working on an edge case but in a monorepo a package can share dependencies and have some of its own.

Could it be possible that the `packagePath` support an array of paths?
If you're ok, I can make a PR for it.

### PR DESCRIPTION
**Pull request by TomerAberbach**
The `packagePath` option can now take an array of `package.json` paths in addition to a single package.json path.

Additionally, if `packagePath` is unspecified (i.e. `undefined`) or is an empty array, then parent directories will be recursively searched for `package.json` files. The search will not go outside of a git repository (determined by looking for a `.git` directory). This is useful for monorepos and should behave normally for single package repositories.

Fixes #6

### CODE REVIEW

**Comment by Septh** [comment]
Great work, seems fine to me, thanks! Just need to update the docs before I merge this. Would you mind? Or I'll do it myself as soon as possible.

**Comment by TomerAberbach** [comment]
I can do it after work (I work 10am to 6pm), but feel free to do it before then if you want to!

**Comment by Septh** [comment]
Thinking about it, I'm just merging right now and I'll update the docs on master for the next release very shortly. Thanks again!

**Comment by TomerAberbach** [comment]
No problem, and sounds good!

**Pull request merged**
